[package]
name = "z-hardware-traits"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["display", "terminal-display"]
display = []
terminal-display = ["display"]

[dependencies]
